name: "Labeler Teste"
on:
  issues:
    types: [ opened, edited, ]
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Add Squad label
        uses: ./
        with:
          add-labels: test